#!/usr/bin/env fish

# Terminate already running bar instances
killall -q waybar

# Wait until the processes have been shut down
#while pgrep -u $UID -x waybar > /dev/null; do sleep 1; done
while pgrep -x waybar > /dev/null
    sleep 1
end

# Launch waybar, using default config location ~/.config/waybar/config
waybar --config ~/.config/waybar/config --style ~/.config/waybar/style.css &

echo "waybar launched..."
