#!/usr/bin/env fish

# Terminate already running bar instances
killall -q waybar

# Wait until the processes have been shut down
#while pgrep -u $UID -x waybar > /dev/null; do sleep 1; done
while pgrep -x waybar > /dev/null
    sleep 1
end

# Launch Polybar, using default config location ~/.config/polybar/config
waybar &
#waybar -c ~/.config/waybar/config -s ~/.config/waybar/style.css > /dev/null 2 &>1 &

echo "waybar launched..."
