#!/usr/bin/env fish

# Terminate already running bar instances
# If all your bars have ipc enabled, you can use
polybar-msg cmd quit
# Otherwise you can use the nuclear option:
#killall -q polybar

# Wait until the processes have benn shut down
#while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done

# Launch Polybar, using default config location ~/.config/polybar/config
#MONITOR=$(polybar -m|tail -1|sed -e 's/:.*$//g')
MONITOR=(polybar -m|tail -1|sed -e 's/:.*$//g') polybar base &
#set -gx MONITOR (polybar -m | tail -1 | sed -e 's/:.*$//g')
#polybar base &

echo "Polybar launched..."
